module MiniMIPS_testbench ();

//reg [29:0] instruction_set [15:0];
//reg [15:0] instruction_set;
//wire result;

initial begin
//you can give here, like below this
//instruction_set = 32'b00000010000100011001000000100000; #10; // rs=$16 rt=$17 rd=$18 s2=s0+s1 		add  s2 s0 s1
//or you can take instructions from file
//readmemb("filename", instruction_set);

//for memory file read & write using followings
//$readmemb("registers.mem", mipsMOdulename.registerModuleName.registers);
//$writememb("registers_outp.mem", mipsMOdulename.registerModuleName.registers);

//Continue for all instruction types 
//Must be least 15*2=30 control lines (There must be at least 2 tests for each instruction)
//You can change the inside of the register.mem file as desired.

//end of the running, output files must be created/updated (register file & data file)

end


endmodule